import = ["/home/luan/.config/alacritty/themes/quixotic.toml"]

[env]
TERM = "alacritty"

[font]
size = 10.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[scrolling]
history = 5000

[window]
opacity = 1.0

[window.padding]
x = 0
y = 0
