[colors.bright]
black = "#3F59AA"
blue = "#008ce3"
cyan = "#3dddd8"
green = "#2ac68e"
magenta = "#a07dde"
red = "#f85858"
white = "#d7d7d7"
yellow = "#f076ab"

[colors.cursor]
cursor = "#f076ab"
text = "CellBackground"

[colors.normal]
black = "#232525"
blue = "#008ce3"
cyan = "#3dddd8"
green = "#2ac68e"
magenta = "#a07dde"
red = "#f85858"
white = "#d7d7d7"
yellow = "#f076ab"

[colors.primary]
background = "#101313"
foreground = "#d7d7d7"
