#!/bin/sh

export PATH="$HOME/.local/bin:$PATH"
[ -d "${CARGO_HOME:-$HOME/.cargo}/bin" ] && export PATH="${CARGO_HOME:-$HOME/.cargo}/bin:$PATH"

# android dev
export ANDROID_HOME="$HOME/Library/Android/sdk"
if [ -d "$ANDROID_HOME" ]; then
    export PATH="$PATH:$ANDROID_HOME/emulator"
    export PATH="$PATH:$ANDROID_HOME/tools"
    export PATH="$PATH:$ANDROID_HOME/platform-tools"
    export PATH="$PATH:$ANDROID_HOME/cmdline-tools/latest/bin"
fi
[ -x "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser" ] && \
    export CHROME_EXECUTABLE="/Applications/Brave Browser.app/Contents/MacOS/Brave Browser"

# texlive (macOS)
if [ -d "$HOME/texlive/2026/bin/universal-darwin" ]; then
    export PATH="$HOME/texlive/2026/bin/universal-darwin:$PATH"
    export MANPATH="$HOME/texlive/2026/texmf-dist/doc/man:$MANPATH"
    export INFOPATH="$HOME/texlive/2026/texmf-dist/doc/info:$INFOPATH"
fi


# export PATH="$HOME/.homebrew/bin:$HOME/.homebrew/sbin:$PATH"
# export HOMEBREW_PREFIX="$HOME/.homebrew
# export HOMEBREW_CELLAR="$HOME/.homebrew/Cellar
# export HOMEBREW_REPOSITORY="$HOME/.homebrew

# export PATH="$(brew --prefix)/bin:$PATH"
# export PATH="/opt/homebrew/bin/:$PATH"

export EDITOR=nvim
