#!/bin/sh

export PATH=$CARGO_HOME/bin:$PATH
export PATH="$HOME/.local/bin":$PATH

# android dev
export ANDROID_HOME=/opt/android-sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/cmdline-tools
export CHROME_EXECUTABLE=/bin/brave

export EDITOR=nvim
